#!/bin/bash

datasource="Patents"
filesuffix="Zipf_distributed"
merge_count=2

java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.GeoReach_Integrate_LoadData LoadMultilevelBitmap $datasource 20 $filesuffix $merge_count
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.GeoReach_Integrate_LoadData LoadMultilevelBitmap $datasource 40 $filesuffix $merge_count
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.GeoReach_Integrate_LoadData LoadMultilevelBitmap $datasource 60 $filesuffix $merge_count
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.GeoReach_Integrate_LoadData LoadMultilevelBitmap $datasource 80 $filesuffix $merge_count

java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar experiment.Experiment_9_27
