#!/bin/bash

datasource="citeseerx"
filesuffix="Zipf_distributed"

java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.Batch_Inserter SetRMBR $datasource 20 $filesuffix
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.Batch_Inserter SetRMBR $datasource 40 $filesuffix
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.Batch_Inserter SetRMBR $datasource 60 $filesuffix
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.Batch_Inserter SetRMBR $datasource 80 $filesuffix

java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.GeoReach_Integrate_LoadData LoadPartialCompresedBitmap $datasource 20 $filesuffix
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.GeoReach_Integrate_LoadData LoadPartialCompresedBitmap $datasource 40 $filesuffix
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.GeoReach_Integrate_LoadData LoadPartialCompresedBitmap $datasource 60 $filesuffix
java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar  def.GeoReach_Integrate_LoadData LoadPartialCompresedBitmap $datasource 80 $filesuffix

java -cp workspace/def/target/def-0.0.1-SNAPSHOT.jar experiment.Experiment_9_27
